### ISSUE TITLE
synchronization behavior for invalid params

### ISSUE THREAD

**Issue by pareshpp** [Seagate/kinetic-protocol#33]
What is the difference between errors thrown for synchronization=False and synchronization=-1?

>>> c = Client('localhost', 8123)
>>> c.connect()
>>> c.put('message','hello world', force="false", synchronization=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/kinetic-py/kinetic-py/kinetic/deprecated/blockingclient.py", line 60, in put
    return self._process(operations.Put(), *args, **kwargs)
  File "/kinetic-py/kinetic-py/kinetic/baseasync.py", line 165, in _process
    return super(BaseAsync, self)._process(op, *args, **kwargs)
  File "/kinetic-py/kinetic-py/kinetic/deprecated/blockingclient.py", line 54, in _process
    return op.onError(e)
  File "/kinetic-py/kinetic-py/kinetic/operations.py", line 110, in onError
    raise e
kinetic.common.KineticMessageException: INVALID_REQUEST: Persistent synchronization option must be set to a valid value
>>> c.put('message','hello world', force="false", synchronization=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/kinetic-py/kinetic-py/kinetic/deprecated/blockingclient.py", line 60, in put
    return self._process(operations.Put(), *args, **kwargs)
  File "/kinetic-py/kinetic-py/kinetic/baseasync.py", line 165, in _process
    return super(BaseAsync, self)._process(op, *args, **kwargs)
  File "/kinetic-py/kinetic-py/kinetic/deprecated/blockingclient.py", line 54, in _process
    return op.onError(e)
  File "/kinetic-py/kinetic-py/kinetic/operations.py", line 110, in onError
    raise e
kinetic.common.KineticMessageException: INVALID_REQUEST: Invalid persistent synchronization option: INVALID_SYNCHRONIZATION
>>>

**Comment by icorderi** [comment]
@pareshpp in general kinetic protocol terms, a **-1** value is invalid and you should **not** be passing those. 

There are also a few python issues:
```python
c.put('message','hello world', force="false", synchronization=False) # wrong
```
- **force** is a _boolean_, you should pass **True** or **False**.
- **synchronization** is an "enum", you can find it in [kinetic.common.Synchronization](https://github.com/Seagate/kinetic-py/blob/master/kinetic/common.py#L246-L250)

The correct use would be:
```python
c.put('message','hello world', force=False, synchronization=Synchronization.WRITEBACK)
// or
c.put('message','hello world')
```
These two are the same because `force=False` and `synchronization=WRITEBACK` are the default values.
